import { apiFetch } from "../api";

export type MessengerContact = { id: string; name: string; avatar?: string | null; city?: string | null; role?: "customer" | "specialist"; online?: boolean; last_seen_at?: string | null };
export type MessengerContext = { id: string; type: "task" | "place" | "application" | "payment"; context_id: string; snapshot?: Record<string, unknown> };
export type MessengerReaction = { user_id: string; emoji: string };
export type MessengerMessage = { id: string; conversation_id: string; sender?: MessengerContact | null; client_message_id?: string | null; kind: string; body?: string | null; reply_to_message_id?: string | null; forwarded_from_message_id?: string | null; metadata?: Record<string, any> | null; reactions?: MessengerReaction[]; receipts?: Array<{ recipient_id: string; delivered_at?: string | null; read_at?: string | null }>; edited_at?: string | null; deleted_at?: string | null; created_at?: string | null };
export type MessengerConversation = { id: string; contact: MessengerContact; last_message?: MessengerMessage | null; last_message_at?: string | null; unread_count: number; pinned_at?: string | null; archived_at?: string | null; muted_until?: string | null; contexts?: MessengerContext[]; created_at?: string | null; updated_at?: string | null };

const root = (path: string, options: RequestInit = {}) => apiFetch(`/messenger${path}`, { namespace: "root", ...options });
export async function listConversations(options: { archived?: boolean; q?: string } = {}): Promise<MessengerConversation[]> { const params = new URLSearchParams({ limit: "100" }); if (options.archived) params.set("archived", "1"); if (options.q) params.set("q", options.q); const payload = await root(`/conversations?${params}`, { method: "GET" }); return Array.isArray(payload?.data) ? payload.data : []; }
export async function getConversation(id: string): Promise<MessengerConversation> { const payload = await root(`/conversations/${id}`, { method: "GET" }); return payload.data; }
export async function createDirectConversation(userId: string, context?: { type: "task" | "place" | "application"; id: number }): Promise<MessengerConversation> { const payload = await root("/conversations/direct", { method: "POST", body: JSON.stringify({ user_id: Number(userId), ...(context ? { context } : {}) }) }); return payload.data; }
export async function listMessages(id: string): Promise<MessengerMessage[]> { const payload = await root(`/conversations/${id}/messages?limit=100`, { method: "GET" }); return Array.isArray(payload?.data) ? payload.data.reverse() : []; }
function uuid() { return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => { const r = Math.random() * 16 | 0; return (c === "x" ? r : (r & 3 | 8)).toString(16); }); }
export async function sendMessengerMessage(id: string, input: { kind?: string; body?: string; metadata?: Record<string, unknown>; reply_to_message_id?: string }): Promise<MessengerMessage> { const payload = await root(`/conversations/${id}/messages`, { method: "POST", body: JSON.stringify({ client_message_id: uuid(), kind: input.kind || "text", body: input.body || null, metadata: input.metadata, reply_to_message_id: input.reply_to_message_id ? Number(input.reply_to_message_id) : null }) }); return payload.data; }
export async function editMessengerMessage(conversationId: string, messageId: string, body: string): Promise<MessengerMessage> { const payload = await root(`/conversations/${conversationId}/messages/${messageId}`, { method: "PATCH", body: JSON.stringify({ body }) }); return payload.data; }
export async function deleteMessengerMessage(conversationId: string, messageId: string): Promise<void> { await root(`/conversations/${conversationId}/messages/${messageId}`, { method: "DELETE" }); }
export async function reactToMessengerMessage(conversationId: string, messageId: string, emoji?: string): Promise<MessengerMessage> { const payload = await root(`/conversations/${conversationId}/messages/${messageId}/reaction`, { method: emoji ? "PUT" : "DELETE", ...(emoji ? { body: JSON.stringify({ emoji }) } : {}) }); return payload.data; }
export async function markMessengerRead(conversationId: string, messageId: string): Promise<void> { await root(`/conversations/${conversationId}/read`, { method: "POST", body: JSON.stringify({ message_id: Number(messageId) }) }); }
export async function updateConversationState(id: string, action: "pin" | "archive" | "mute", enabled: boolean): Promise<void> { await root(`/conversations/${id}/${action}`, { method: enabled ? "PUT" : "DELETE", ...(action === "mute" && enabled ? { body: JSON.stringify({ muted_until: new Date(Date.now() + 365 * 86400000).toISOString() }) } : {}) }); }
export async function searchMessenger(q: string): Promise<Array<{ conversation_id: string; message: MessengerMessage }>> { const payload = await root(`/search?q=${encodeURIComponent(q)}`, { method: "GET" }); return Array.isArray(payload?.data) ? payload.data : []; }
export async function forwardMessengerMessage(conversationId: string, messageId: string): Promise<MessengerMessage> { const payload = await root(`/conversations/${conversationId}/forward`, { method: "POST", body: JSON.stringify({ message_id: Number(messageId), client_message_id: uuid() }) }); return payload.data; }
