import React, { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { SafeAreaView } from "react-native-safe-area-context";
import { useNavigation } from "@react-navigation/native";
import { fetchBalanceTransactions, type BalanceTransaction } from "../src/services/account";
import { colors, radius, spacing, typography } from "../src/theme";
export default function BalanceHistoryScreen() { const navigation = useNavigation(); const [items, setItems] = useState<BalanceTransaction[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { fetchBalanceTransactions().then(setItems).finally(() => setLoading(false)); }, []); return <SafeAreaView style={styles.root}><View style={styles.header}><TouchableOpacity style={styles.icon} onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={27} color={colors.textPrimary} /></TouchableOpacity><Text style={styles.title}>История операций</Text><View style={styles.icon} /></View>{loading ? <ActivityIndicator style={styles.loader} /> : <FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.row}><View style={[styles.rowIcon, item.direction === "income" ? styles.incomeIcon : styles.expenseIcon]}><Ionicons name={item.direction === "income" ? "arrow-up" : "cart-outline"} size={23} color={item.direction === "income" ? colors.success : colors.danger} /></View><View style={styles.copy}><Text style={styles.rowTitle}>{item.title}</Text>{item.description ? <Text numberOfLines={1} style={styles.description}>{item.description}</Text> : null}<Text style={styles.date}>{item.created_at ? new Date(item.created_at).toLocaleString("ru-RU") : ""}</Text></View><Text style={[styles.amount, item.direction === "income" ? styles.income : styles.expense]}>{item.amount > 0 ? "+" : ""}{Math.round(item.amount).toLocaleString("ru-RU")} ₽</Text></View>} ListEmptyComponent={<View style={styles.empty}><Ionicons name="receipt-outline" size={42} color={colors.textTertiary} /><Text style={styles.emptyText}>Операций пока нет</Text></View>} />}</SafeAreaView>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.white }, header: { height: 58, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.md }, icon: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, title: { ...typography.section }, loader: { marginTop: 100 }, list: { padding: spacing.lg, flexGrow: 1 }, row: { minHeight: 82, flexDirection: "row", alignItems: "center", gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.divider }, rowIcon: { width: 48, height: 48, borderRadius: radius.full, alignItems: "center", justifyContent: "center" }, incomeIcon: { backgroundColor: colors.successSoft }, expenseIcon: { backgroundColor: colors.dangerSoft }, copy: { flex: 1 }, rowTitle: { ...typography.bodyMedium }, description: { ...typography.meta, color: colors.textSecondary }, date: { ...typography.meta, color: colors.textTertiary, marginTop: 2 }, amount: { ...typography.bodyMedium }, income: { color: colors.success }, expense: { color: colors.danger }, empty: { alignItems: "center", marginTop: 100 }, emptyText: { ...typography.secondary, color: colors.textSecondary, marginTop: spacing.md } });
