import React from "react";
import { StyleSheet, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { SafeAreaView } from "react-native-safe-area-context";
import { useNavigation, useRoute, type RouteProp } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { AppText, Button } from "../components/ui";
import { colors, radius, spacing } from "../src/theme";
import type { RootStackParamList } from "../src/navigation/types";
type Nav = NativeStackNavigationProp<RootStackParamList>; type R = RouteProp<RootStackParamList, "MasterSelected">;
export default function MasterSelectedScreen() { const navigation = useNavigation<Nav>(); const { params } = useRoute<R>(); return <SafeAreaView style={styles.root} edges={["top", "bottom", "left", "right"]}><View style={styles.content}><View style={styles.check}><Ionicons name="checkmark" size={58} color={colors.success} /></View><AppText variant="display" style={styles.center}>Мастер выбран!</AppText><AppText variant="body" tone="secondary" style={styles.subtitle}>Обсудите детали в личном чате и следите за выполнением работы в заявке.</AppText><View style={styles.timeline}><Timeline done title="Заявка опубликована" /><Timeline done title="Мастер выбран" /><Timeline title="Выполнение работы" /><Timeline title="Завершение и отзыв" /></View><View style={styles.actions}>{params.chatId ? <Button label="Перейти в чат" leftIcon={<Ionicons name="chatbubble-ellipses-outline" size={20} color={colors.textPrimary} />} onPress={() => navigation.replace("ChatDetail", { chatId: params.chatId! })} /> : null}<Button label="Посмотреть заявку" variant="secondary" onPress={() => navigation.replace("TaskDetail", { taskId: params.taskId })} style={styles.secondary} /></View></View></SafeAreaView>; }
function Timeline({ done = false, title }: { done?: boolean; title: string }) { return <View style={styles.timelineRow}><View style={[styles.timelineIcon, done && styles.timelineDone]}><Ionicons name={done ? "checkmark" : "ellipse-outline"} size={16} color={done ? colors.surface : colors.textTertiary} /></View><AppText variant="secondary" tone={done ? "primary" : "secondary"}>{title}</AppText></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, content: { flex: 1, alignItems: "center", padding: spacing.xl, paddingTop: 70 }, center: { textAlign: "center", marginTop: spacing.lg }, subtitle: { maxWidth: 320, textAlign: "center", marginTop: spacing.sm }, check: { width: 116, height: 116, borderRadius: 58, backgroundColor: colors.successSoft, alignItems: "center", justifyContent: "center" }, timeline: { width: "100%", marginTop: spacing.xxl, padding: spacing.lg, backgroundColor: colors.surfaceSecondary, borderRadius: radius.xl, gap: spacing.lg }, timelineRow: { flexDirection: "row", alignItems: "center", gap: spacing.md }, timelineIcon: { width: 28, height: 28, borderRadius: 14, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" }, timelineDone: { borderColor: colors.success, backgroundColor: colors.success }, actions: { width: "100%", marginTop: "auto" }, secondary: { marginTop: spacing.sm } });
