import React, { useEffect, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { SafeAreaView } from "react-native-safe-area-context";
import { useNavigation, useRoute, type RouteProp } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { getNotification, type AppNotification } from "../src/services/notifications";
import { colors, radius, spacing, typography } from "../src/theme";
import type { RootStackParamList } from "../src/navigation/types";

type Nav = NativeStackNavigationProp<RootStackParamList>;
type R = RouteProp<RootStackParamList, "NotificationDetail">;

export default function NotificationDetailScreen() {
  const navigation = useNavigation<Nav>(); const route = useRoute<R>();
  const [item, setItem] = useState<AppNotification | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { getNotification(route.params.notificationId).then(setItem).catch((e) => setError(e instanceof Error ? e.message : String(e))); }, [route.params.notificationId]);
  const openAction = () => { if (!item) return; const data = item.data || {}; const taskId = String(data.task_id || ""); const placeId = String(data.place_id || ""); const chatId = String(data.chat_id || ""); const conversationId = String(data.conversation_id || ""); const specialistId = String(data.specialist_id || data.user_id || ""); if (conversationId) navigation.navigate("MessengerChat", { conversationId }); else if (chatId) navigation.navigate("ChatDetail", { chatId }); else if (taskId) navigation.navigate("TaskDetail", { taskId }); else if (placeId) navigation.navigate("PlaceDetail", { placeId }); else if (specialistId) navigation.navigate("PublicProfile", { specialistId }); else navigation.goBack(); };
  return <SafeAreaView style={styles.root} edges={["top", "bottom", "left", "right"]}><View style={styles.header}><TouchableOpacity style={styles.icon} onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={27} color={colors.textPrimary} /></TouchableOpacity><Text style={styles.headerTitle}>Уведомление</Text><View style={styles.icon} /></View>{!item && !error ? <ActivityIndicator style={styles.loader} color={colors.textPrimary} /> : error ? <View style={styles.center}><Ionicons name="cloud-offline-outline" size={44} color={colors.textTertiary} /><Text style={styles.error}>{error}</Text></View> : item ? <View style={styles.content}><View style={styles.eventIcon}><Ionicons name="notifications-outline" size={33} color={colors.textPrimary} /></View><Text style={styles.title}>{item.title}</Text>{item.created_at ? <Text style={styles.date}>{new Date(item.created_at).toLocaleString("ru-RU")}</Text> : null}{item.body ? <View style={styles.bodyCard}><Text style={styles.body}>{item.body}</Text></View> : null}<TouchableOpacity style={styles.primary} onPress={openAction}><Text style={styles.primaryText}>{actionLabel(item)}</Text></TouchableOpacity></View> : null}</SafeAreaView>;
}
function actionLabel(item: AppNotification) { if (item.type === "message") return "Перейти к сообщению"; if (item.type === "application") return "Перейти к заявке"; if (item.type === "like" || item.type === "favorite" || item.type === "comment") return "Посмотреть Плейс"; if (item.type === "follower") return "Открыть профиль"; return "Готово"; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.white }, header: { height: 58, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.md }, icon: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, headerTitle: { ...typography.section }, loader: { marginTop: 100 }, center: { alignItems: "center", padding: spacing.xl, marginTop: 90 }, error: { ...typography.secondary, color: colors.textSecondary, textAlign: "center", marginTop: spacing.md }, content: { flex: 1, alignItems: "center", padding: spacing.xl }, eventIcon: { width: 76, height: 76, borderRadius: 38, backgroundColor: colors.accentSoft, alignItems: "center", justifyContent: "center", marginTop: spacing.xl }, title: { ...typography.display, color: colors.textPrimary, textAlign: "center", marginTop: spacing.xl }, date: { ...typography.meta, color: colors.textSecondary, marginTop: spacing.xs }, bodyCard: { alignSelf: "stretch", padding: spacing.lg, backgroundColor: colors.surfaceSecondary, borderRadius: radius.xl, marginTop: spacing.xl }, body: { ...typography.body, color: colors.textPrimary }, primary: { alignSelf: "stretch", height: 54, backgroundColor: colors.accent, borderRadius: radius.full, alignItems: "center", justifyContent: "center", marginTop: spacing.xl }, primaryText: { ...typography.button, color: colors.textPrimary } });
