import React, { useEffect, useState } from "react";
import { ActivityIndicator, StyleSheet, Switch, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { SafeAreaView } from "react-native-safe-area-context";
import { useNavigation } from "@react-navigation/native";
import { getNotificationPreferences, updateNotificationPreferences, type NotificationPreferences } from "../src/services/notifications";
import { colors, radius, spacing, typography } from "../src/theme";

const defaults: NotificationPreferences = { push_enabled: true, messages: true, requests: true, applications: true, favorites: true, comments: true, likes: true, followers: true };
export default function NotificationSettingsScreen() {
  const navigation = useNavigation(); const [value, setValue] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null);
  useEffect(() => { getNotificationPreferences().then((data) => setValue({ ...defaults, ...data })).finally(() => setLoading(false)); }, []);
  const toggle = async (key: keyof NotificationPreferences) => { const next = !value[key]; setValue((current) => ({ ...current, [key]: next })); setSaving(key); try { const saved = await updateNotificationPreferences({ [key]: next }); setValue((current) => ({ ...current, ...saved })); } finally { setSaving(null); } };
  return <SafeAreaView style={styles.root} edges={["top", "bottom", "left", "right"]}><View style={styles.header}><TouchableOpacity style={styles.icon} onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={27} color={colors.textPrimary} /></TouchableOpacity><Text style={styles.title}>Уведомления</Text><View style={styles.icon} /></View>{loading ? <ActivityIndicator style={styles.loader} /> : <View style={styles.content}><View style={styles.intro}><View style={styles.introIcon}><Ionicons name="notifications-outline" size={28} color={colors.textPrimary} /></View><View style={styles.introCopy}><Text style={styles.introTitle}>Настройте уведомления</Text><Text style={styles.introText}>Получайте только важные для вас события.</Text></View></View><View style={styles.group}><Setting label="Все push-уведомления" hint="Включить или выключить уведомления на устройстве" value={value.push_enabled} busy={saving === "push_enabled"} onChange={() => void toggle("push_enabled")} /></View><Text style={styles.section}>Основные</Text><View style={styles.group}><Setting icon="chatbubble-outline" label="Сообщения" hint="Новые сообщения от пользователей" value={value.messages} busy={saving === "messages"} onChange={() => void toggle("messages")} /><Setting icon="document-text-outline" label="Новые заявки" hint="События ваших заявок" value={value.requests} busy={saving === "requests"} onChange={() => void toggle("requests")} /><Setting icon="people-outline" label="Отклики" hint="Новые предложения мастеров" value={value.applications} busy={saving === "applications"} onChange={() => void toggle("applications")} /><Setting icon="heart-outline" label="Избранное" hint="Когда сохраняют ваши работы" value={value.favorites} busy={saving === "favorites"} onChange={() => void toggle("favorites")} /></View><Text style={styles.section}>Плейсы и профиль</Text><View style={styles.group}><Setting icon="chatbox-ellipses-outline" label="Комментарии" value={value.comments} busy={saving === "comments"} onChange={() => void toggle("comments")} /><Setting icon="heart-outline" label="Лайки" value={value.likes} busy={saving === "likes"} onChange={() => void toggle("likes")} /><Setting icon="person-add-outline" label="Подписки" value={value.followers} busy={saving === "followers"} onChange={() => void toggle("followers")} /></View></View>}</SafeAreaView>;
}
function Setting({ icon, label, hint, value, busy, onChange }: { icon?: keyof typeof Ionicons.glyphMap; label: string; hint?: string; value: boolean; busy?: boolean; onChange: () => void }) { return <View style={styles.row}>{icon ? <Ionicons name={icon} size={22} color={colors.textPrimary} /> : null}<View style={styles.copy}><Text style={styles.label}>{label}</Text>{hint ? <Text style={styles.hint}>{hint}</Text> : null}</View>{busy ? <ActivityIndicator size="small" /> : <Switch value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.success }} thumbColor={colors.white} />}</View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.white }, header: { height: 58, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.md }, icon: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, title: { ...typography.section }, loader: { marginTop: 100 }, content: { padding: spacing.lg }, intro: { minHeight: 94, backgroundColor: colors.accentSoft, borderRadius: radius.xl, flexDirection: "row", alignItems: "center", gap: spacing.md, padding: spacing.lg }, introIcon: { width: 54, height: 54, borderRadius: 27, backgroundColor: colors.accent, alignItems: "center", justifyContent: "center" }, introCopy: { flex: 1 }, introTitle: { ...typography.bodyMedium }, introText: { ...typography.secondary, color: colors.textSecondary, marginTop: 2 }, section: { ...typography.section, marginTop: spacing.xl, marginBottom: spacing.sm }, group: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, overflow: "hidden", marginTop: spacing.lg }, row: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: spacing.md, paddingHorizontal: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.divider }, copy: { flex: 1 }, label: { ...typography.body, color: colors.textPrimary }, hint: { ...typography.meta, color: colors.textSecondary, marginTop: 2 } });
