import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useFocusEffect, useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { TabScreenLayout } from "../components/TabScreenLayout";
import { TaskCardRow, type TaskItem } from "../components/TaskCardRow";
import { apiFetch } from "../src/api";
import { colors } from "../src/theme";
import type { RootStackParamList } from "../src/navigation/types";
type Nav = NativeStackNavigationProp<RootStackParamList>; type Tab = "mine" | "responses" | "available";
export default function RequestsHubScreen() { const navigation = useNavigation<Nav>(); const [tab, setTab] = useState<Tab>("mine"); const [items, setItems] = useState<TaskItem[]>([]); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); try { const path = tab === "mine" ? "/tasks/mine" : tab === "responses" ? "/applications/mine" : "/tasks"; const data = await apiFetch(path, { method: "GET" }); const raw = Array.isArray(data) ? data : Array.isArray(data?.data) ? data.data : []; setItems(tab === "responses" ? raw.map((row: any) => row.task || row.proffi_task || row).filter((row: any) => row?.id) : raw); } catch { setItems([]); } finally { setLoading(false); } }, [tab]); useFocusEffect(useCallback(() => { void load(); }, [load])); return <TabScreenLayout><View style={styles.header}><Text style={styles.title}>Заявки</Text><TouchableOpacity onPress={() => navigation.navigate("ChatList")}><Text style={styles.chat}>Чаты</Text></TouchableOpacity></View><View style={styles.tabs}><TabButton active={tab === "mine"} label="Мои заявки" onPress={() => setTab("mine")} /><TabButton active={tab === "responses"} label="Мои отклики" onPress={() => setTab("responses")} /><TabButton active={tab === "available"} label="Доступные" onPress={() => setTab("available")} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{loading ? <ActivityIndicator color={colors.black} style={{ marginTop: 40 }} /> : items.length ? <View style={styles.list}>{items.map((task) => <TaskCardRow key={String(task.id)} task={task} onPress={() => navigation.navigate("TaskDetail", { taskId: String(task.id) })} />)}</View> : <View style={styles.empty}><Text style={styles.emptyTitle}>{tab === "mine" ? "У вас пока нет заявок" : tab === "responses" ? "Откликов пока нет" : "Нет доступных заявок"}</Text><Text style={styles.emptyText}>{tab === "mine" ? "Создайте заявку через центральную кнопку +" : "Здесь появятся новые работы и ваши предложения."}</Text></View>}{tab === "mine" ? <TouchableOpacity style={styles.create} onPress={() => navigation.navigate("AIRequest")}><Text style={styles.createText}>＋ Создать новую заявку</Text></TouchableOpacity> : null}</ScrollView></TabScreenLayout>; }
function TabButton({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { return <TouchableOpacity style={[styles.tab, active && styles.tabActive]} onPress={onPress}><Text style={[styles.tabText, active && styles.tabTextActive]}>{label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 18, paddingTop: 13, paddingBottom: 14 }, title: { fontSize: 28, fontWeight: "900" }, chat: { color: "#5D6C91", fontSize: 15, fontWeight: "800" }, tabs: { flexDirection: "row", gap: 7, paddingHorizontal: 14, paddingBottom: 13 }, tab: { flex: 1, minHeight: 43, borderRadius: 15, backgroundColor: "#F1F3F6", alignItems: "center", justifyContent: "center", paddingHorizontal: 5 }, tabActive: { backgroundColor: colors.accent }, tabText: { fontSize: 12, textAlign: "center", fontWeight: "700" }, tabTextActive: { fontWeight: "900" }, content: { padding: 14, paddingBottom: 30 }, list: { gap: 11 }, empty: { alignItems: "center", borderRadius: 22, backgroundColor: "#F6F7F9", padding: 30, marginTop: 22 }, emptyTitle: { fontSize: 19, fontWeight: "900" }, emptyText: { color: colors.navInactive, textAlign: "center", lineHeight: 20, marginTop: 8 }, create: { minHeight: 58, borderRadius: 18, backgroundColor: colors.accent, alignItems: "center", justifyContent: "center", marginTop: 15 }, createText: { fontSize: 17, fontWeight: "900" } });
